quarkus:
  datasource:
    db-kind: ${DB_KIND}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    jdbc:
      url: ${DB_URL}
  hibernate-orm:
    database:
      generation: validate
  flyway:
    migrate-at-start: true
    locations: classpath:db/migration